### ISSUE TITLE
Tag a release of the latest version of the api-client

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-sps-ogc-processes-api-client-python#4]
Need a release of the unity-sps-ogc process (currently what's in dev) to be merged to main, released/tagged so that it can be referenced by the unity-sds-client code base in a reproducible manner.

**Comment by drewm-swe** [comment]
Prior to tagging, we're going to need to merge in the changes from my `ogc-processes-api-register` branch. There have been some interface changes in `unity-sps-ogc-processes-api` repo

**Comment by drewm-swe** [comment]
This is complete
